import Vue from 'vue'
import Vuetify, {
  VApp,
  VContainer,
  VRow,
  VCol,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VList,
  VListItem,
  VListItemContent,
  VListItemTitle,
  VListItemSubtitle,
  VListItemAction,
  VForm,
  VInput,
  VFileInput,
  VTextField,
  VTextarea,
  VSelect,
  VCombobox,
  VAutocomplete,
  VBtn,
  VIcon,
  VDialog,
  VDataTable,
  VChip,
  VTooltip,
  VToolbar,
  VToolbarTitle,
  VPagination,
  VProgressLinear,
  VSpacer,
  VFooter,
  VExpandTransition,
} from 'vuetify/lib'

Vue.use(Vuetify, {
  components: {
    VApp,
    VContainer,
    VRow,
    VCol,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VList,
    VListItem,
    VListItemContent,
    VListItemTitle,
    VListItemSubtitle,
    VListItemAction,
    VForm,
    VInput,
    VFileInput,
    VTextField,
    VTextarea,
    VSelect,
    VCombobox,
    VAutocomplete,
    VBtn,
    VIcon,
    VDialog,
    VDataTable,
    VChip,
    VTooltip,
    VToolbar,
    VToolbarTitle,
    VPagination,
    VProgressLinear,
    VSpacer,
    VFooter,
    VExpandTransition,
  },
})

export default new Vuetify({
  theme: {
    themes: {
      light: {
        primary: '#4181a1',
        secondary: '#86c1e0',
        accent: '#554475',
        error: '#d1534f',
        info: '#fee0a1',
        success: '#6cb77e',
        warning: '#f08264',
      },
    },
  },
})
